version: '3.9'

services:
  frontend:
    image: 086627396918.dkr.ecr.ap-south-1.amazonaws.com/my-frontend:latest
    container_name: myapp-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    image: 086627396918.dkr.ecr.ap-south-1.amazonaws.com/my-backend:latest
    container_name: myapp-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/libricore
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - uploads-volume:/usr/src/app/uploads

  mongo:
    image: mongo:6
    container_name: myapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
  uploads-volume: